//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "champion_star")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub champion_id: String,
    pub star: i32,
    pub health: i32,
    pub damage: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::champion::Entity",
        from = "Column::ChampionId",
        to = "super::champion::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Champion,
}

impl Related<super::champion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Champion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
